{
 "title": "My dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "s21_mem_free", "legendFormat": "__auto" },
    { "expr": "s21_mem_used", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "s21_disk_available", "legendFormat": "__auto" },
    { "expr": "s21_disk_used", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "s21_cpu_usage", "legendFormat": "__auto" }
   ]
  }
 ]
}